# =========================
# BANCO DE DADOS
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/nfe

spring.datasource.username=postgres

spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JWT
# =========================
logging.level.org.springframework.security=DEBUG
api.security.token.secret=automacao-nfe-jwt-secret

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# =========================
# SERVIDOR
# =========================

server.port=8080